### ISSUE TITLE
Android minimum SDK version 24

### ISSUE THREAD

**Issue by octopi** [YoussefHenna/expo-enode-link-sdk#16]
First, thanks so much for maintaining this library!

And thanks for the recent bump to Link SDK version 1.0.0. I did however notice that the module still suggests Android `minSdkVersion` < 24 is compatible. In the latest version of the Android SDK (v1.0.0), the minimum API level has changed to 24: https://developers.enode.com/docs/link-sdks/android#minimum-api-level

**Comment by YoussefHenna** [comment]
Nice catch. I'll update the read-me.
