### ISSUE TITLE
minSdkVersion 23 cannot be smaller than version 24 declared in library [io.enode:linkkit:1.0.0]

### ISSUE THREAD

**Issue by ceniklas** [YoussefHenna/expo-enode-link-sdk#19]
## Issue
Package versions: 
```
"@youssefhenna/expo-enode-link-sdk": "^1.0.1",
"expo": "51.0.15",
```

Using expo 51 without any changes to the `expo-build-properties` property give the following error:

```
Execution failed for task ':app:processReleaseMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 23 cannot be smaller than version 24 declared in library [io.enode:linkkit:1.0.0] /home/expo/.gradle/caches/transforms-4/5170c040820f562642941eca1f3ffe83/transformed/jetified-linkkit-1.0.0/AndroidManifest.xml as the library might be using APIs not available in 23
  	Suggestion: use a compatible library with a minSdk of at most 23,
  		or increase this project's minSdk version to at least 24,
or use tools:overrideLibrary="io.enode.link" to force usage (may lead to runtime failures)
```

Looks like the minSdkVersion was bumped to 24 but Expo still uses 23. 

There is also a mismatch in the examples given in the README.md where the Android section specifies 24 but the summary 23.

## Workaround
Our workaround for now is to overrides expos minSdkVersion in app.config.ts
```
[
  'expo-build-properties',
  {
    android: {
      minSdkVersion: 24,
    },
  },
],
```

**Comment by YoussefHenna** [comment]
Thanks for the heads up on the mismatch in the readme, I've updated that. Otherwise I don't think there's any action needed from my end, the readme specifies that you need to set the min sdk version to 24
