### ISSUE TITLE
Android: Missing 'success' resultcode

### ISSUE THREAD

**Issue by bjornevik** [YoussefHenna/expo-enode-link-sdk#7]
Hi!

Thanks for this plugin!

When running on iOS I get a `'success'` code once the onboarding has finished. On android I do not get any code once the onboarding has finished, but I still get other codes, like for instance the `'cancelledByUser'` code.

I can't really see any reason why the current [handling](https://github.com/YoussefHenna/expo-enode-link-sdk/blob/main/android/src/main/java/expo/modules/enodelinksdk/ExpoEnodeLinkSDKModule.kt#L59) shouldn't work. Though to be fair I'm not particularly familiar with native android code or the SDKs for that matter.

**Comment by YoussefHenna** [comment]
Hey! Are you getting any other code in place of the expected `'success`? Or just nothing?

**Comment by bjornevik** [comment]
1. No code on success. 

2. When I close the window I get the expected cancelledByUser

**Comment by YoussefHenna** [comment]
Odd, we're currently in contact with the Enode team regarding another issue faced on android so we haven't been able to test the full flow on android yet. But I'll mention this and let you know when I hear back.

**Comment by bjornevik** [comment]
Seems like the problem was that I was passing a normal url (ex. https://google.com) instead of passing a `myapp://`-uri, to the redirectUri field in the API-call. Working now 😄

**Comment by YoussefHenna** [comment]
Glad you got it sorted!
